version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: .
    container_name: user_routes_app
    depends_on:
      - db  
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    networks:
      - app_network
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
